"""Performance analysis, metrics, visualization, and tearsheet generation."""

from backtester.analysis.metrics import (
    PerformanceMetrics,
    RoundTripTrade,
    alpha,
    annualized_return,
    average_drawdown,
    average_trade_duration,
    average_win_loss_ratio,
    beta,
    cagr,
    calculate_metrics,
    calculate_returns,
    calmar_ratio,
    downside_deviation,
    drawdown_series,
    expectancy,
    extract_round_trips,
    max_drawdown,
    max_drawdown_duration,
    profit_factor,
    sharpe_ratio,
    snapshots_to_dataframe,
    sortino_ratio,
    total_return,
    trades_to_dataframe,
    volatility,
    win_rate,
)
from backtester.analysis.tearsheet import (
    MonthlyReturns,
    Tearsheet,
    YearlyReturns,
    generate_tearsheet,
)
from backtester.analysis.visualization import (
    create_performance_dashboard,
    plot_cumulative_returns,
    plot_drawdown,
    plot_equity_curve,
    plot_monthly_returns,
    plot_portfolio_composition,
    plot_returns_distribution,
    plot_rolling_sharpe,
    plot_trade_pnl,
    plot_trades_on_price,
)

__all__ = [
    # Metrics
    "PerformanceMetrics",
    "RoundTripTrade",
    "alpha",
    "annualized_return",
    "average_drawdown",
    "average_trade_duration",
    "average_win_loss_ratio",
    "beta",
    "cagr",
    "calculate_metrics",
    "calculate_returns",
    "calmar_ratio",
    "downside_deviation",
    "drawdown_series",
    "expectancy",
    "extract_round_trips",
    "max_drawdown",
    "max_drawdown_duration",
    "profit_factor",
    "sharpe_ratio",
    "snapshots_to_dataframe",
    "sortino_ratio",
    "total_return",
    "trades_to_dataframe",
    "volatility",
    "win_rate",
    # Tearsheet
    "MonthlyReturns",
    "Tearsheet",
    "YearlyReturns",
    "generate_tearsheet",
    # Visualization
    "create_performance_dashboard",
    "plot_cumulative_returns",
    "plot_drawdown",
    "plot_equity_curve",
    "plot_monthly_returns",
    "plot_portfolio_composition",
    "plot_returns_distribution",
    "plot_rolling_sharpe",
    "plot_trade_pnl",
    "plot_trades_on_price",
]
